import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, ScanSearch, GraduationCap, Flag, LayoutDashboard, ArrowRight, LockKeyhole, LogIn, UserPlus, ClipboardList, LogOut } from "lucide-react";
import { TermsBox } from "./components/TermsBox";
import { Learn } from "./components/Learn";
import { withScanLoading } from "./services/scanLoading";
import { api } from './services/api';
import './styles.css';
import { Dashboard } from "./components/Dashboards";
import { ScanResult as Result } from './components/ScanResult';
import { Report, ReportManagement, ThreatIndicators } from './components/Reports';

const nav = [{id:'scanner',label:'Scanner',icon:ScanSearch},{id:'learn',label:'Learn',icon:GraduationCap},{id:'report',label:'Report',icon:Flag}];
const sample = 'From: Security Team <security-alert@paypaI-account.com>\nSubject: Urgent: Your account will be limited\n\nVerify your account immediately at https://paypal-secure-login.net/verify. Please confirm your password and card details.';

function pageFromUrl(){const id=window.location.hash.slice(1);return id||'scanner';}
function App(){
 const [page,setPage]=useState(pageFromUrl),[auth,setAuth]=useState(null),[user,setUser]=useState(null),[text,setText]=useState(''),[ran,setRan]=useState(false);
 const [reportSource,setReportSource]=useState(null);
 const [authReady,setAuthReady]=useState(false),[accountError,setAccountError]=useState(''),[loggingOut,setLoggingOut]=useState(false);
 useEffect(()=>{let active=true;api.auth.me().then(session=>{if(active)setUser(session.user)}).catch(()=>{}).finally(()=>{if(active)setAuthReady(true)});return ()=>{active=false}},[]);
 // Sync browser back/forward to page state
 useEffect(()=>{
   const onPop=()=>setPage(pageFromUrl());
   window.addEventListener('popstate',onPop);
   return ()=>window.removeEventListener('popstate',onPop);
 },[]);
 const go=(p,source=null)=>{if((p==='user-dashboard'||p==='learn')&&!user){setAuth('login');return}if(p.startsWith('admin-')&&user?.role!=='admin')return;if(p==='report')setReportSource(source);if(p!==page){window.history.pushState(null,'','#'+p);}setPage(p)}; const dashboard=user?.role==='admin'?'admin-dashboard':'user-dashboard';
 async function submit(form){const session=auth==='signup'?await api.auth.signup(form):await api.auth.login(form);api.scans.clear();setUser(session.user);setAccountError('');setAuth(null);const dest=session.user.role==='admin'?'admin-dashboard':'user-dashboard';window.history.pushState(null,'','#'+dest);setPage(dest);}
 async function logout(){if(loggingOut)return;setLoggingOut(true);setAccountError('');try{await api.auth.logout();api.scans.clear();setUser(null);setReportSource(null);setText('');setRan(false);window.history.pushState(null,'','#scanner');setPage('scanner')}catch(error){setAccountError(error.message)}finally{setLoggingOut(false)}}
 if(auth)return <Auth key={auth} mode={auth} setMode={setAuth} submit={submit}/>;
 return <div className="app"><header><button className="brand" onClick={()=>go(user?.role==='admin'?'admin-dashboard':'scanner')}><span className="brandmark"><ShieldCheck size={25}/></span><span>De<span>Phish</span></span></button><nav>{user?.role==='admin'?<><button className={page==='admin-dashboard'?'active':''} onClick={()=>go('admin-dashboard')}><LayoutDashboard size={17}/>Dashboard</button><button className={page==='admin-reports'?'active':''} onClick={()=>go('admin-reports')}><ClipboardList size={17}/>Scan Reports</button><button className={page==='admin-indicators'?'active':''} onClick={()=>go('admin-indicators')}><ShieldCheck size={17}/>Threat Indicators</button></>:<>{nav.map(n=><button className={page===n.id?'active':''} onClick={()=>go(n.id)} key={n.id}><n.icon size={17}/>{n.label}</button>)}<button className={page==='user-dashboard'?'active':''} onClick={()=>go(dashboard)}><LayoutDashboard size={17}/>Dashboard</button></>}</nav>{user?<div className="account"><button className="profile" onClick={()=>go(dashboard)}>{user.name.slice(0,2).toUpperCase()}</button><button className="logout" disabled={loggingOut} onClick={logout}><LogOut size={15}/> Log out</button></div>:<div className="authActions"><button disabled={!authReady} onClick={()=>setAuth('login')}>Log in</button><button className="primary small" disabled={!authReady} onClick={()=>setAuth('signup')}>Sign up</button></div>}</header>{accountError&&<p className="scanError" role="alert">{accountError}</p>}<main>{page==='scanner'&&<Scanner text={text} setText={setText} ran={ran} setRan={setRan} go={go}/>} {page==='learn'&&user&&<Learn user={user}/>} {page==='report'&&<Report key={reportSource?.sourceScanId || reportSource?.message || 'manual'} source={reportSource} authenticated={Boolean(user)}/>} {page==='admin-indicators'&&user?.role==='admin'&&<ThreatIndicators/>} {page==='user-dashboard'&&user&&<Dashboard go={go}/>} {page==='admin-dashboard'&&user?.role==='admin'&&<Dashboard admin go={go}/>} {page==='admin-reports'&&user?.role==='admin'&&<ReportManagement/>}</main></div>
}
function Auth({mode,setMode,submit}){const signup=mode==='signup';const [f,setF]=useState({name:'',email:'',password:''});const [busy,setBusy]=useState(false),[error,setError]=useState('');async function onSubmit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await submit(f)}catch(err){setError(err.message)}finally{setBusy(false)}}return <main className="authPage"><button className="brand authBrand" disabled={busy} onClick={()=>setMode(null)}><span className="brandmark"><ShieldCheck size={25}/></span><span>De<span>Phish</span></span></button><section className="authCard"><span className="authIcon">{signup?<UserPlus/>:<LogIn/>}</span><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Start scanning and keep your security history in one place.':'Log in to view your previous scans and reports.'}</p><form onSubmit={onSubmit} aria-busy={busy}>{signup&&<label>Full name<input required maxLength={80} autoComplete="name" disabled={busy} placeholder="Your name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>}<label>Email address<input required maxLength={254} autoComplete="email" disabled={busy} type="email" placeholder="you@example.com" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input required type="password" disabled={busy} autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={72} placeholder={signup?'At least 12 characters':'Your password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{error&&<p className="scanError" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Log in'} <ArrowRight size={16}/></button></form><div className="authSwitch">{signup?'Already have an account?':'New to DePhish?'} <button disabled={busy} onClick={()=>setMode(signup?'login':'signup')}>{signup?'Log in':'Create an account'}</button></div></section></main>}
function Scanner({text,setText,ran,setRan,go}){const [tosAccepted,setTosAccepted]=useState(false);const [loading,setLoading]=useState(false),[error,setError]=useState('');
 async function analyze(){if(loading||!tosAccepted)return;setLoading(true);setError('');setRan(false);try{setRan(await withScanLoading(()=>api.scans.analyze(text,'auto',{tosAccepted: Boolean(tosAccepted), termsVersion: tosAccepted})))}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <><section className="hero"><div className="eyebrow"><span/>PHISHING DETECTION & AWARENESS</div><h1>Think before you click.</h1><p>Check suspicious messages in seconds. Learn the signs. Stay one step ahead of phishing.</p></section><section className="scannerWrap"><div className="scannerCard"><div className="cardTop"><div><h2>Scan a suspicious message</h2><p>Paste any message you want to check — an email, an SMS, or just a link. Scanning also contacts detected links to check domain and certificate details. Saved reports mask recognized personal identifiers and secrets. Signed-in scans also appear in your history.</p></div><span className="secure"><LockKeyhole size={15}/> Secure scan</span></div><textarea aria-label="Message to scan" maxLength={5000} disabled={loading} value={text} onChange={e=>{setText(e.target.value);setRan(false);setError('')}} placeholder="Paste an email, SMS, or link to analyze..."/><TermsBox checked={tosAccepted} onChange={setTosAccepted} disabled={loading}/><div className="scanFoot"><button className="sample" disabled={loading} onClick={()=>setText(sample)}>Try a sample message <ArrowRight size={15}/></button><span>{text.length}/5,000 characters</span><button className="primary" disabled={loading||!text.trim()||!tosAccepted} onClick={analyze}><ScanSearch className={loading?"scanSpinner":undefined} size={18}/>{loading?'Analyzing…':'Analyze message'}</button></div>{loading&&<p className="scanLoading" role="status">Analyzing your message and available link evidence…</p>}{error&&<p className="scanError" role="alert">{error}</p>}</div>{ran&&<Result result={ran} go={p=>go(p,{message:text,sourceScanId:ran.persistence?.scope==='account'?ran.persistence.id:undefined})}/>}</section></>}
createRoot(document.getElementById("root")).render(<App/>);
