import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, ScanSearch, GraduationCap, Flag, LayoutDashboard, ArrowRight, CheckCircle2, AlertTriangle, Link2, LockKeyhole, Mail, MessageSquare, LogIn, UserPlus, History, Eye, ClipboardList, Phone, LogOut, X } from 'lucide-react';
import { api } from './services/api';
import './styles.css';

const nav = [{id:'scanner',label:'Scanner',icon:ScanSearch},{id:'learn',label:'Learn',icon:GraduationCap},{id:'report',label:'Report',icon:Flag}];
const sample = 'From: Security Team <security-alert@paypaI-account.com>\nSubject: Urgent: Your account will be limited\n\nVerify your account immediately at https://paypal-secure-login.net/verify. Please confirm your password and card details.';

function App(){
 const [page,setPage]=useState('scanner'),[auth,setAuth]=useState(null),[user,setUser]=useState(null),[text,setText]=useState(''),[ran,setRan]=useState(false);
 const [authReady,setAuthReady]=useState(false),[accountError,setAccountError]=useState(''),[loggingOut,setLoggingOut]=useState(false);
 useEffect(()=>{let active=true;api.auth.me().then(session=>{if(active)setUser(session.user)}).catch(()=>{}).finally(()=>{if(active)setAuthReady(true)});return ()=>{active=false}},[]);
 const go=p=>{if(p==='user-dashboard'&&!user){setAuth('login');return}if(p.startsWith('admin-')&&user?.role!=='admin')return;setPage(p)}; const dashboard=user?.role==='admin'?'admin-dashboard':'user-dashboard';
 async function submit(form){const session=auth==='signup'?await api.auth.signup(form):await api.auth.login(form);api.scans.clear();setUser(session.user);setAccountError('');setAuth(null);setPage(session.user.role==='admin'?'admin-dashboard':'user-dashboard')}
 async function logout(){if(loggingOut)return;setLoggingOut(true);setAccountError('');try{await api.auth.logout();api.scans.clear();setUser(null);setText('');setRan(false);setPage('scanner')}catch(error){setAccountError(error.message)}finally{setLoggingOut(false)}}
 if(auth)return <Auth key={auth} mode={auth} setMode={setAuth} submit={submit}/>;
 return <div className="app"><header><button className="brand" onClick={()=>go(user?.role==='admin'?'admin-dashboard':'scanner')}><span className="brandmark"><ShieldCheck size={25}/></span><span>De<span>Phish</span></span></button><nav>{user?.role==='admin'?<><button className={page==='admin-dashboard'?'active':''} onClick={()=>go('admin-dashboard')}><LayoutDashboard size={17}/>Dashboard</button><button className={page==='admin-reports'?'active':''} onClick={()=>go('admin-reports')}><ClipboardList size={17}/>Reports</button></>:<>{nav.map(n=><button className={page===n.id?'active':''} onClick={()=>go(n.id)} key={n.id}><n.icon size={17}/>{n.label}</button>)}<button className={page==='user-dashboard'?'active':''} onClick={()=>go(dashboard)}><LayoutDashboard size={17}/>Dashboard</button></>}</nav>{user?<div className="account"><button className="profile" onClick={()=>go(dashboard)}>{user.name.slice(0,2).toUpperCase()}</button><button className="logout" disabled={loggingOut} onClick={logout}><LogOut size={15}/> Log out</button></div>:<div className="authActions"><button disabled={!authReady} onClick={()=>setAuth('login')}>Log in</button><button className="primary small" disabled={!authReady} onClick={()=>setAuth('signup')}>Sign up</button></div>}</header>{accountError&&<p className="scanError" role="alert">{accountError}</p>}<main>{page==='scanner'&&<Scanner text={text} setText={setText} ran={ran} setRan={setRan} go={go}/>} {page==='learn'&&<Learn/>} {page==='report'&&<Report/>} {page==='user-dashboard'&&user&&<UserDashboard go={go}/>} {page==='admin-dashboard'&&user?.role==='admin'&&<AdminDashboard/>} {page==='admin-reports'&&user?.role==='admin'&&<ReportManagement/>}</main></div>
}
function Auth({mode,setMode,submit}){const signup=mode==='signup';const [f,setF]=useState({name:'',email:'',password:''});const [busy,setBusy]=useState(false),[error,setError]=useState('');async function onSubmit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await submit(f)}catch(err){setError(err.message)}finally{setBusy(false)}}return <main className="authPage"><button className="brand authBrand" disabled={busy} onClick={()=>setMode(null)}><span className="brandmark"><ShieldCheck size={25}/></span><span>De<span>Phish</span></span></button><section className="authCard"><span className="authIcon">{signup?<UserPlus/>:<LogIn/>}</span><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Start scanning and keep your security history in one place.':'Log in to view your previous scans and reports.'}</p><form onSubmit={onSubmit} aria-busy={busy}>{signup&&<label>Full name<input required maxLength={80} autoComplete="name" disabled={busy} placeholder="Your name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>}<label>Email address<input required maxLength={254} autoComplete="email" disabled={busy} type="email" placeholder="you@example.com" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input required type="password" disabled={busy} autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={72} placeholder={signup?'At least 12 characters':'Your password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{error&&<p className="scanError" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Log in'} <ArrowRight size={16}/></button></form><div className="authSwitch">{signup?'Already have an account?':'New to DePhish?'} <button disabled={busy} onClick={()=>setMode(signup?'login':'signup')}>{signup?'Log in':'Create an account'}</button></div></section></main>}
function Scanner({text,setText,ran,setRan,go}){const [type,setType]=useState('email'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function analyze(){if(loading)return;setLoading(true);setError('');setRan(false);try{setRan(await api.scans.analyze(text,type))}catch(e){setError(e.message)}finally{setLoading(false)}}
 function changeType(value){setType(value);setRan(false);setError('')}
 return <><section className="hero"><div className="eyebrow"><span/>PHISHING DETECTION & AWARENESS</div><h1>Think before you click.</h1><p>Check suspicious messages in seconds. Learn the signs. Stay one step ahead of phishing.</p></section><section className="scannerWrap"><div className="scannerCard"><div className="cardTop"><div><h2>Scan a suspicious message</h2><p>Paste an email, SMS, or online message below to check for phishing signs.</p></div><span className="secure"><LockKeyhole size={15}/> Secure scan</span></div><div className="tabs"><button className={type==='email'?'selected':''} disabled={loading} onClick={()=>changeType('email')}><Mail size={16}/> Email</button><button className={type==='sms'?'selected':''} disabled={loading} onClick={()=>changeType('sms')}><MessageSquare size={16}/> SMS / Message</button></div><textarea aria-label="Message to scan" maxLength={5000} disabled={loading} value={text} onChange={e=>{setText(e.target.value);setRan(false);setError('')}} placeholder="Paste the message you received here..."/><div className="scanFoot"><button className="sample" disabled={loading} onClick={()=>{setText(sample);changeType('email')}}>Try a sample message <ArrowRight size={15}/></button><span>{text.length}/5,000 characters</span><button className="primary" disabled={loading||!text.trim()} onClick={analyze}><ScanSearch size={18}/>{loading?'Analyzing…':'Analyze message'}</button></div>{error&&<p className="scanError" role="alert">{error}</p>}</div>{ran&&<Result result={ran} go={go}/>}</section></>}
function urlExplanation(url){
 const reasons=[];
 if(url.is_ip)reasons.push('Uses an IP address instead of a named domain.');
 if(url.has_at_symbol)reasons.push('Contains an @ symbol; check the actual destination hostname.');
 if(url.is_shortener)reasons.push('Uses a shortener that hides the final destination.');
 if(url.is_suspicious_tld)reasons.push('Uses a domain suffix flagged by a heuristic rule. This alone does not establish fraud.');
 if(url.excessive_subdomains)reasons.push('Has multiple subdomains; inspect the domain carefully.');
 return reasons.join(' ')||'A link was found. Its presence alone does not establish whether it is safe or malicious.';
}
function Result({result,go}){const low=result.prediction==='Legitimate',medium=result.prediction==='Suspicious';return <div className={'result '+(low?'lowRisk':medium?'mediumRisk':'highRisk')} aria-live="polite"><div className="riskHead"><div className="riskRing"><b>{result.risk_score}</b><small>/100</small></div><div><span className="highpill">{result.risk_level}</span><h2>{low?'No phishing detected':medium?'Suspicious message detected':'Potential phishing detected'}</h2><p>{low?'The model estimates low risk. This does not verify the sender or guarantee that the message is safe.':'This message has suspicious signs. Verify the sender before interacting.'}</p></div><button className="outline" onClick={()=>go('report')}><Flag size={16}/> Report this</button></div><div className="findings"><h3>What we found</h3><p>These are pattern matches, not proof of fraud or a complete explanation of the model’s decision.</p>{result.detected_indicators.map((item,i)=><div className="finding" key={item.category+'-'+i}><span><AlertTriangle size={18}/></span><div><b>{item.title}</b><p>{item.description}</p>{item.matched_terms?.length>0&&<p className="matchedTerms">{item.matched_terms.map((term,j)=><mark key={j}>{term}</mark>)}</p>}</div></div>)}{result.detected_urls.map((item,i)=><div className="finding" key={i}><span><Link2 size={18}/></span><div><b>Link found: {item.hostname}</b><p className="detectedUrl">{item.url}</p><p>{urlExplanation(item)}</p></div></div>)}{!result.detected_indicators.length&&!result.detected_urls.length&&<p>No phishing indicators or links were found.</p>}<div className="scanAdvice"><b>What to do next</b><p>{low?"If the message asks for money or personal details, verify it through the official app or a known contact.":"Avoid the message’s links and do not share passwords or OTPs. Open the official app yourself or contact the organization using a known number."}</p><small>The score is the model’s estimate, not a guarantee. Sender identity and live website reputation have not been verified.</small></div></div></div>}
function Learn(){return <section className="content"><div className="eyebrow"><span/>CYBERSECURITY AWARENESS</div><h1>Learn to recognize the signs.</h1><p className="lead">Short, practical lessons that help you stay safer online every day.</p></section>}
function Report(){return <section className="content narrow"><div className="eyebrow"><span/>COMMUNITY PROTECTION</div><h1>Report a phishing attempt.</h1><p className="lead">Your report helps identify threats and protect others. You can report anonymously.</p><form className="reportForm"><label>Describe what happened<textarea placeholder="Tell us about the suspicious message or incident..."/></label><label>Suspicious link or sender<input placeholder="https://... or sender@example.com"/></label><button className="primary submit"><Flag size={17}/> Submit report</button></form></section>}
function UserDashboard({go}){const [scans,setScans]=useState([]),[selected,setSelected]=useState(null);useEffect(()=>{api.scans.list().then(setScans)},[]);return <section className="content"><div className="dashTitle"><div><div className="eyebrow"><span/>MY SECURITY</div><h1>Scan history</h1><p className="lead">Review earlier checks and revisit their findings anytime.</p></div><button className="primary" onClick={()=>go('scanner')}><ScanSearch size={16}/> New scan</button></div><div className="metricGrid userMetrics"><Metric icon={History} color="blue" num={scans.length||'—'} text="Saved scans"/><Metric icon={AlertTriangle} color="red" num={scans.filter(s=>s.status==='Suspicious').length||'—'} text="Threats flagged"/><Metric icon={CheckCircle2} color="teal" num={scans.filter(s=>s.status==='Low risk').length||'—'} text="Low-risk messages"/></div><section className="panel historyPanel"><div className="panelHead"><h2>Previous scans</h2><span>Current session</span></div>{scans.map(s=><div className="historyRow" key={s.id}><span className="typeIcon">{s.type==='SMS'?<MessageSquare/>:<Mail/>}</span><div><b>{s.title}</b><p>{s.type} · {s.date} · Score {s.score}/100</p></div><Status status={s.status}/><button className="outline" onClick={()=>setSelected(s)}><Eye size={15}/> View result</button></div>)}</section>{selected&&<div className="modalShade"><section className="detailModal"><button className="close" onClick={()=>setSelected(null)}><X/></button><span className="lesson">SCAN RESULT · {selected.id}</span><h2>{selected.title}</h2><Status status={selected.status}/><div className="detailScore"><b>{selected.score}</b><span>Risk score / 100</span></div><p>{selected.summary}</p></section></div>}</section>}
function AdminDashboard(){return <section className="content"><div className="eyebrow"><span/>ADMIN OVERVIEW</div><h1>Threat dashboard</h1><p className="lead">Monitor reported phishing activity and common attack patterns.</p><div className="metricGrid"><Metric icon={Flag} color="red" num="1,284" text="Reports this month"/><Metric icon={AlertTriangle} color="amber" num="38%" text="High-risk reports"/><Metric icon={ShieldCheck} color="blue" num="842" text="Users protected"/><Metric icon={ScanSearch} color="purple" num="4,906" text="Messages scanned"/></div></section>}
function ReportManagement(){const [reports,setReports]=useState([]),[filter,setFilter]=useState('All');useEffect(()=>{api.reports.list().then(setReports)},[]);const visible=reports.filter(r=>filter==='All'||r.category===filter);async function update(id,status){await api.reports.updateStatus(id,status);setReports(x=>x.map(r=>r.id===id?{...r,status}:r))}return <section className="content"><div className="eyebrow"><span/>ADMIN REVIEW</div><h1>Report management</h1><p className="lead">Triage community-submitted URLs, emails, and phone numbers.</p><div className="filters">{['All','URL','Email','Phone number'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><section className="panel reportTable"><div className="tableHead"><span>Submitted item</span><span>Reporter</span><span>Received</span><span>Status</span><span>Review</span></div>{visible.map(r=><div className="tableRow" key={r.id}><div className="reportedValue"><span className="typeIcon">{r.category==='URL'?<Link2/>:r.category==='Email'?<Mail/>:<Phone/>}</span><div><b>{r.value}</b><small>{r.category} · {r.id}</small></div></div><span>{r.reporter}</span><span>{r.submitted}</span><Status status={r.status}/><select value={r.status} onChange={e=>update(r.id,e.target.value)}>{['Pending','Suspicious','Verified','False positive'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section></section>}
function Status({status}){return <span className={'status '+status.toLowerCase().replace(' ','-')}>{status}</span>};function Metric({icon:I,color,num,text}){return <div className="metric"><span className={'metricIcon '+color}><I/></span><b>{num}</b><p>{text}</p></div>};createRoot(document.getElementById('root')).render(<App/>);
