import React, { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { PasswordInput } from './PasswordInput';
export function AccountSecurity({ api }) {
  const [state, setState] = useState(null), [password, setPassword] = useState(''), [code, setCode] = useState(''), [pending, setPending] = useState(null), [cooldown, setCooldown] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  useEffect(() => { api.security().then(setState).catch(e => setError(e.message)); }, [api]);
  useEffect(() => { if (!cooldown) return; const timer = setTimeout(() => setCooldown(value => value - 1), 1000); return () => clearTimeout(timer); }, [cooldown]);
  async function request(enabled) { setBusy(true); setError(''); setNotice(''); try { await api.requestMfa({ password, enabled }); setPending(enabled); setCooldown(60); setNotice('A 6-digit confirmation code was sent to your email.'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function verify(e) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.verifyMfaSetting({ code, enabled: pending }); setState({ ...state, mfaEnabled: result.mfaEnabled }); setPending(null); setCode(''); setPassword(''); setNotice(`Email MFA is now ${result.mfaEnabled ? 'enabled' : 'disabled'}.`); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className="authCard" style={{ margin: '48px auto' }}><span className="authIcon"><ShieldCheck/></span><h1>Account security</h1><p>Protect sign-ins with a one-time email code. When disabled, your usual email and password login stays unchanged.</p>{state && <><p>Email MFA is <strong>{state.mfaEnabled ? 'enabled' : 'disabled'}</strong>.</p>{pending === null ? <form onSubmit={e => { e.preventDefault(); request(!state.mfaEnabled); }}><label>Current password<PasswordInput required autoComplete="current-password" placeholder="Enter password" value={password} onChange={e => setPassword(e.target.value)}/></label>{error && <p className="scanError" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>{busy ? 'Please wait…' : state.mfaEnabled ? 'Disable email MFA' : 'Enable email MFA'}</button></form> : <form onSubmit={verify}><label>6-digit confirmation code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="Enter OTP" value={code} onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}/></label><button type="button" className="authForgot" disabled={busy || cooldown > 0} onClick={() => request(pending)}>{cooldown ? `Resend code in ${cooldown}s` : 'Resend code'}</button>{error && <p className="scanError" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>Confirm change</button></form>}{notice && <p className="authNotice" role="status">{notice}</p>}</>}</section>;
}
